version: '3.9'

services:
  database:
    image: postgres
    restart: always
    container_name: postgres
    hostname: db
    ports: 
      - "5432:5432"
    env_file:
      - .env
    volumes:
       - db:/var/lib/postgresql/data
volumes:
  db: 
