version: '3.9'

services:
  database:
    image: postgres
    restart: always
    container_name: postgres
    hostname: db
    ports: 
      - "5432:5432"
    env_file:
      - .env
    volumes:
       - db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
volumes:
  db: 
